# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Algorithm')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50)),
                ('attritute_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_file', models.CharField(max_length=150)),
                ('dataset_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('owner', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('description', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=150)),
                ('people_editing', models.BooleanField()),
                ('datasets', models.ManyToManyField(to='core.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.ManyToManyField(to='core.Analysis')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=254)),
                ('username', models.CharField(max_length=150)),
                ('is_superuser', models.BooleanField()),
                ('password', models.CharField(max_length=32)),
                ('projects', models.ManyToManyField(through='core.Ownership', to='core.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Visibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Visualization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.TextField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Analysis')),
            ],
        ),
        migrations.CreateModel(
            name='VisualizationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='visualization',
            name='visualization_types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.VisualizationType'),
        ),
        migrations.AddField(
            model_name='project',
            name='visibilities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Visibility'),
        ),
        migrations.AddField(
            model_name='ownership',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project'),
        ),
        migrations.AddField(
            model_name='ownership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='datasets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Dataset'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='dataset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Dataset'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project'),
        ),
    ]
