# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reports',
            new_name='Report',
        ),
        migrations.RenameField(
            model_name='analysis',
            old_name='algorithms',
            new_name='algorithm',
        ),
        migrations.RenameField(
            model_name='analysis',
            old_name='projects',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='attribute',
            old_name='attribute_types',
            new_name='attribute_type',
        ),
        migrations.RenameField(
            model_name='attribute',
            old_name='datasets',
            new_name='dataset',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='datasets',
            new_name='dataset',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='visibilities',
            new_name='visibility',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='projects',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='visualization',
            old_name='visualization_types',
            new_name='visualization_type',
        ),
    ]
