# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171010_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='dataset_file',
            field=models.FileField(upload_to=''),
        ),
    ]
