# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171012_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='name',
            field=models.CharField(default='Analysis1', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
