# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171016_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Dataset'),
        ),
    ]
