# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171028_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='analysis',
            name='analysis_status',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='core.AnalysisStatus'),
            preserve_default=False,
        ),
    ]
