# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20171031_0923'),
        ('core', '0006_auto_20171023_1707'),
    ]

    operations = [
    ]
