# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20171102_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Analysis')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('analysis_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AnalysisType')),
            ],
        ),
        migrations.AddField(
            model_name='argument',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Parameter'),
        ),
    ]
