# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20171121_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='creation_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.CreationStatus'),
        ),
    ]
