# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 23:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20171213_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownership',
            name='project',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='user',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='dataset',
            new_name='datasets',
        ),
        migrations.RemoveField(
            model_name='user',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Ownership',
        ),
    ]
