# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20171220_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Dataset'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='core.Project'),
        ),
    ]
