# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-08 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20180202_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='visualization',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='visualization',
            name='visualization_type',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Visualization',
        ),
        migrations.DeleteModel(
            name='VisualizationType',
        ),
    ]
